//Constantes
export const CONSTANTS = {
  GET_USER_TASKS: "GET_USER_TASKS",
  GET_HELP_TASKS: "GET_HELP_TASKS",
  SET_TASK_DETAILS: "SET_TASK_DETAILS",
  POST_NOTE:"POST_NOTE",
  PUT_MODIFYING_TASK:"PUT_MODIFYING_TASK" 
}
