const CREATE_PROJECT = "CREATE_PROJECT";
const GET_ALL_USERS = "GET_ALL_USERS";
const SET_USER = "SET_USER";
const GET_PROJECTS_BY_USER = "GET_PROJECTS_BY_USER";

module.exports = {
  CREATE_PROJECT,
  GET_ALL_USERS,
  SET_USER,
  GET_PROJECTS_BY_USER,
};
