const SET_USER = "SET_USER";
const SET_SOCKET = "SET_SOCKET";
const GET_NOTIFICATIONS = "GET_NOTIFICATIONS";
const GET_ALL_NOTIFICATIONS = "GET_ALL_NOTIFICATIONS";
const READ_NOTIFICATIONS = "READ_NOTIFICATIONS";

module.exports = {
  SET_USER,
  SET_SOCKET,
  GET_NOTIFICATIONS,
  READ_NOTIFICATIONS,
  GET_ALL_NOTIFICATIONS
};
