const GET_NOTES_DETAILS = "GET_NOTES_DETAILS";
const CLEAR_NOTES = "CLEAR_NOTES";
const CREATE_NOTE = "CREATE_NOTE";
const REMOVE_NOTE = "REMOVE_NOTE";
const GET_ADVERTISEMENTS = "GET_ADVERTISEMENTS";
const CREATE_ADVERTISEMENT = "CREATE_ADVERTISEMENT";
const DELETE_ADVERTISEMENT = "DELETE_ADVERTISEMENT";
const CLEAR_ADVERTISEMENTS = "CLEAR_ADVERTISEMENTS"

module.exports = { 
    GET_NOTES_DETAILS, 
    CLEAR_NOTES, 
    CREATE_NOTE, 
    REMOVE_NOTE, 
    GET_ADVERTISEMENTS, 
    CREATE_ADVERTISEMENT, 
    DELETE_ADVERTISEMENT,
    CLEAR_ADVERTISEMENTS,
};
