const GET_NOTES_DETAILS = "GET_NOTES_DETAILS";
const CLEAR_NOTES = "CLEAR_NOTES";
const CREATE_NOTE = "CREATE_NOTE";
const REMOVE_NOTE = "REMOVE_NOTE";

module.exports = { GET_NOTES_DETAILS, CLEAR_NOTES, CREATE_NOTE, REMOVE_NOTE };
