module.exports = [
  {
    _id: "61313b4dfc13ae1dd2000cf8",
    projectName: "Regrant",
    creationDate: "2020-11-26T22:45:54Z",
    requiredDate: "2021-02-06T22:54:37Z",
    description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    sprintCount: 17,
    currentSprint: 2,
    sprintDuration: 7,
    status: 21.8,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000cf9" },
    projectName: "Veribet",
    creationDate: "2021-01-11T03:31:13Z",
    requiredDate: "2020-09-16T15:38:00Z",
    description:
      "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.",
    sprintCount: 5,
    currentSprint: 4,
    sprintDuration: 6,
    status: 77.63,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000cfa" },
    projectName: "Alphazap",
    creationDate: "2021-07-05T22:56:54Z",
    requiredDate: "2020-11-12T23:10:45Z",
    description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    sprintCount: 16,
    currentSprint: 9,
    sprintDuration: 11,
    status: 89.56,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000cfb" },
    projectName: "Asoka",
    creationDate: "2020-11-14T11:34:21Z",
    requiredDate: "2020-11-11T12:56:39Z",
    description:
      "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    sprintCount: 18,
    currentSprint: 3,
    sprintDuration: 2,
    status: 70.48,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000cfc" },
    projectName: "Mat Lam Tam",
    creationDate: "2021-02-16T05:02:36Z",
    requiredDate: "2021-04-07T21:38:03Z",
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    sprintCount: 7,
    currentSprint: 19,
    sprintDuration: 11,
    status: 18.37,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000cfd" },
    projectName: "Home Ing",
    creationDate: "2020-11-04T14:04:31Z",
    requiredDate: "2020-10-29T14:55:56Z",
    description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    sprintCount: 15,
    currentSprint: 18,
    sprintDuration: 15,
    status: 44.96,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000cfe" },
    projectName: "Flowdesk",
    creationDate: "2021-07-13T18:06:39Z",
    requiredDate: "2021-04-12T17:41:58Z",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    sprintCount: 12,
    currentSprint: 18,
    sprintDuration: 14,
    status: 16.16,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000cff" },
    projectName: "Holdlamis",
    creationDate: "2021-05-20T07:51:25Z",
    requiredDate: "2021-08-18T02:38:59Z",
    description:
      "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
    sprintCount: 8,
    currentSprint: 10,
    sprintDuration: 15,
    status: 99.75,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000d00" },
    projectName: "Veribet",
    creationDate: "2021-01-04T01:44:06Z",
    requiredDate: "2020-12-02T13:13:35Z",
    description:
      "Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.",
    sprintCount: 3,
    currentSprint: 8,
    sprintDuration: 15,
    status: 90.94,
  },
  {
    _id: { $oid: "61313b4dfc13ae1dd2000d01" },
    projectName: "Transcof",
    creationDate: "2021-02-12T07:56:26Z",
    requiredDate: "2021-02-27T12:24:11Z",
    description:
      "In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.\n\nMaecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
    sprintCount: 1,
    currentSprint: 3,
    sprintDuration: 18,
    status: 60.86,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d02" },
    projectName: "Job",
    creationDate: "2021-04-05T07:59:53Z",
    requiredDate: "2021-08-22T23:01:43Z",
    description:
      "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    sprintCount: 8,
    currentSprint: 20,
    sprintDuration: 16,
    status: 57.41,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d03" },
    projectName: "Bytecard",
    creationDate: "2021-02-19T03:14:34Z",
    requiredDate: "2021-03-26T23:56:45Z",
    description:
      "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    sprintCount: 5,
    currentSprint: 17,
    sprintDuration: 7,
    status: 11.85,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d04" },
    projectName: "Regrant",
    creationDate: "2020-11-19T00:45:58Z",
    requiredDate: "2020-09-20T03:03:06Z",
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    sprintCount: 14,
    currentSprint: 13,
    sprintDuration: 8,
    status: 3.23,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d05" },
    projectName: "Konklab",
    creationDate: "2020-09-21T09:26:30Z",
    requiredDate: "2020-11-04T21:56:58Z",
    description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
    sprintCount: 19,
    currentSprint: 14,
    sprintDuration: 20,
    status: 54.45,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d06" },
    projectName: "Flexidy",
    creationDate: "2020-12-20T07:46:02Z",
    requiredDate: "2021-05-26T07:43:11Z",
    description:
      "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
    sprintCount: 15,
    currentSprint: 14,
    sprintDuration: 6,
    status: 15.56,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d07" },
    projectName: "Fixflex",
    creationDate: "2020-11-01T04:16:19Z",
    requiredDate: "2021-03-15T09:57:27Z",
    description:
      "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
    sprintCount: 10,
    currentSprint: 14,
    sprintDuration: 12,
    status: 71.26,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d08" },
    projectName: "Home Ing",
    creationDate: "2021-08-20T20:09:24Z",
    requiredDate: "2021-05-25T23:46:38Z",
    description:
      "Fusce consequat. Nulla nisl. Nunc nisl.\n\nDuis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
    sprintCount: 13,
    currentSprint: 8,
    sprintDuration: 6,
    status: 20.32,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d09" },
    projectName: "Wrapsafe",
    creationDate: "2021-05-21T18:29:33Z",
    requiredDate: "2020-12-24T04:41:45Z",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    sprintCount: 6,
    currentSprint: 5,
    sprintDuration: 4,
    status: 67.7,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d0a" },
    projectName: "Sub-Ex",
    creationDate: "2021-05-01T17:48:31Z",
    requiredDate: "2021-07-02T18:11:58Z",
    description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    sprintCount: 9,
    currentSprint: 12,
    sprintDuration: 10,
    status: 61.54,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d0b" },
    projectName: "Asoka",
    creationDate: "2021-05-19T22:24:18Z",
    requiredDate: "2020-12-24T23:56:42Z",
    description:
      "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.\n\nMorbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    sprintCount: 15,
    currentSprint: 19,
    sprintDuration: 18,
    status: 93.96,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d0c" },
    projectName: "Tres-Zap",
    creationDate: "2021-08-18T21:00:12Z",
    requiredDate: "2021-01-01T08:54:07Z",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.",
    sprintCount: 3,
    currentSprint: 8,
    sprintDuration: 3,
    status: 84.77,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d0d" },
    projectName: "Bigtax",
    creationDate: "2020-09-17T02:04:08Z",
    requiredDate: "2021-07-12T22:45:04Z",
    description:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    sprintCount: 15,
    currentSprint: 17,
    sprintDuration: 19,
    status: 38.45,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d0e" },
    projectName: "Transcof",
    creationDate: "2021-03-08T04:37:44Z",
    requiredDate: "2021-06-17T11:36:40Z",
    description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
    sprintCount: 8,
    currentSprint: 1,
    sprintDuration: 9,
    status: 39.59,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d0f" },
    projectName: "Fix San",
    creationDate: "2021-05-06T11:04:18Z",
    requiredDate: "2020-09-30T02:15:31Z",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    sprintCount: 6,
    currentSprint: 6,
    sprintDuration: 15,
    status: 99.01,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d10" },
    projectName: "Gembucket",
    creationDate: "2021-08-24T22:12:58Z",
    requiredDate: "2020-09-12T02:54:02Z",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    sprintCount: 14,
    currentSprint: 13,
    sprintDuration: 17,
    status: 57.25,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d11" },
    projectName: "Ventosanzap",
    creationDate: "2021-01-06T02:07:06Z",
    requiredDate: "2021-06-07T03:33:32Z",
    description:
      "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
    sprintCount: 20,
    currentSprint: 19,
    sprintDuration: 2,
    status: 14.72,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d12" },
    projectName: "Sub-Ex",
    creationDate: "2020-11-29T15:35:35Z",
    requiredDate: "2020-11-29T03:24:02Z",
    description:
      "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    sprintCount: 19,
    currentSprint: 8,
    sprintDuration: 15,
    status: 16.26,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d13" },
    projectName: "Tin",
    creationDate: "2021-08-14T20:28:32Z",
    requiredDate: "2021-04-21T04:12:29Z",
    description:
      "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
    sprintCount: 9,
    currentSprint: 18,
    sprintDuration: 11,
    status: 84.7,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d14" },
    projectName: "Y-Solowarm",
    creationDate: "2020-11-20T12:36:23Z",
    requiredDate: "2021-05-08T01:50:42Z",
    description:
      "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.\n\nCurabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    sprintCount: 1,
    currentSprint: 3,
    sprintDuration: 11,
    status: 81.34,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d15" },
    projectName: "Ronstring",
    creationDate: "2021-02-16T11:52:30Z",
    requiredDate: "2021-06-13T00:18:48Z",
    description:
      "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
    sprintCount: 13,
    currentSprint: 9,
    sprintDuration: 13,
    status: 71.64,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d16" },
    projectName: "Home Ing",
    creationDate: "2021-03-20T08:51:48Z",
    requiredDate: "2021-01-13T08:59:13Z",
    description:
      "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
    sprintCount: 19,
    currentSprint: 12,
    sprintDuration: 15,
    status: 51.86,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d17" },
    projectName: "Kanlam",
    creationDate: "2021-06-27T17:35:00Z",
    requiredDate: "2021-08-14T21:01:58Z",
    description: "Fusce consequat. Nulla nisl. Nunc nisl.",
    sprintCount: 15,
    currentSprint: 2,
    sprintDuration: 8,
    status: 77.41,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d18" },
    projectName: "Veribet",
    creationDate: "2020-10-07T19:35:04Z",
    requiredDate: "2021-01-19T15:58:57Z",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.\n\nMauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
    sprintCount: 10,
    currentSprint: 18,
    sprintDuration: 15,
    status: 51.65,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d19" },
    projectName: "Konklab",
    creationDate: "2021-01-29T11:24:05Z",
    requiredDate: "2020-11-19T12:06:51Z",
    description:
      "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    sprintCount: 5,
    currentSprint: 6,
    sprintDuration: 4,
    status: 23.01,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d1a" },
    projectName: "Solarbreeze",
    creationDate: "2021-03-13T20:41:30Z",
    requiredDate: "2021-02-05T10:39:59Z",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    sprintCount: 14,
    currentSprint: 4,
    sprintDuration: 3,
    status: 30.39,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d1b" },
    projectName: "Alpha",
    creationDate: "2021-02-25T13:56:06Z",
    requiredDate: "2020-09-10T06:33:58Z",
    description:
      "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    sprintCount: 2,
    currentSprint: 16,
    sprintDuration: 19,
    status: 19.08,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d1c" },
    projectName: "Konklux",
    creationDate: "2021-06-08T22:42:22Z",
    requiredDate: "2021-03-20T17:45:43Z",
    description:
      "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    sprintCount: 8,
    currentSprint: 14,
    sprintDuration: 16,
    status: 32.33,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d1d" },
    projectName: "Job",
    creationDate: "2021-07-16T02:54:55Z",
    requiredDate: "2021-08-08T07:41:17Z",
    description:
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    sprintCount: 20,
    currentSprint: 10,
    sprintDuration: 6,
    status: 60.01,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d1e" },
    projectName: "Lotlux",
    creationDate: "2021-04-17T09:50:18Z",
    requiredDate: "2021-08-09T23:59:39Z",
    description:
      "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
    sprintCount: 2,
    currentSprint: 16,
    sprintDuration: 20,
    status: 60.93,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d1f" },
    projectName: "Zaam-Dox",
    creationDate: "2021-03-25T16:49:58Z",
    requiredDate: "2021-03-17T04:09:17Z",
    description:
      "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
    sprintCount: 10,
    currentSprint: 5,
    sprintDuration: 7,
    status: 21.96,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d20" },
    projectName: "Regrant",
    creationDate: "2021-04-10T15:03:51Z",
    requiredDate: "2021-03-20T00:58:44Z",
    description:
      "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.\n\nDuis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
    sprintCount: 17,
    currentSprint: 18,
    sprintDuration: 11,
    status: 36.77,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d21" },
    projectName: "Ronstring",
    creationDate: "2020-12-07T20:25:26Z",
    requiredDate: "2021-04-21T11:11:27Z",
    description:
      "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.\n\nProin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    sprintCount: 15,
    currentSprint: 2,
    sprintDuration: 1,
    status: 20.72,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d22" },
    projectName: "Prodder",
    creationDate: "2020-12-29T21:13:10Z",
    requiredDate: "2021-08-19T22:55:42Z",
    description:
      "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    sprintCount: 2,
    currentSprint: 10,
    sprintDuration: 1,
    status: 82.91,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d23" },
    projectName: "Treeflex",
    creationDate: "2021-07-10T22:19:29Z",
    requiredDate: "2021-04-17T22:54:36Z",
    description:
      "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    sprintCount: 16,
    currentSprint: 15,
    sprintDuration: 12,
    status: 39.34,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d24" },
    projectName: "Opela",
    creationDate: "2021-05-23T18:31:09Z",
    requiredDate: "2021-04-28T18:36:39Z",
    description:
      "Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
    sprintCount: 18,
    currentSprint: 19,
    sprintDuration: 14,
    status: 51.21,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d25" },
    projectName: "Bitchip",
    creationDate: "2021-08-10T12:56:13Z",
    requiredDate: "2020-12-23T10:11:11Z",
    description:
      "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    sprintCount: 2,
    currentSprint: 6,
    sprintDuration: 14,
    status: 48.24,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d26" },
    projectName: "Fintone",
    creationDate: "2020-10-22T06:32:23Z",
    requiredDate: "2021-01-12T23:15:23Z",
    description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
    sprintCount: 3,
    currentSprint: 1,
    sprintDuration: 16,
    status: 36.18,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d27" },
    projectName: "Lotstring",
    creationDate: "2021-08-05T15:37:59Z",
    requiredDate: "2020-10-12T09:06:12Z",
    description:
      "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
    sprintCount: 17,
    currentSprint: 15,
    sprintDuration: 1,
    status: 33.11,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d28" },
    projectName: "Job",
    creationDate: "2021-06-21T09:29:50Z",
    requiredDate: "2021-02-03T06:23:40Z",
    description:
      "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    sprintCount: 11,
    currentSprint: 15,
    sprintDuration: 7,
    status: 74.94,
  },
  {
    _id: { $oid: "61313b4efc13ae1dd2000d29" },
    projectName: "Trippledex",
    creationDate: "2021-06-13T08:46:45Z",
    requiredDate: "2020-11-01T12:55:08Z",
    description:
      "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.\n\nCum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    sprintCount: 14,
    currentSprint: 9,
    sprintDuration: 20,
    status: 99.84,
  },
];
