const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
const GET_TASKS_BY_PROJECT = "GET_TASKS_BY_PROJECT";
const GET_ASIGNED_USERS = "GET_ASIGNED_USERS";
const DELETE_PROJECT = "DELETE_PROJECT";
const GET_ALL_USERS = "GET_ALL_USERS";
const ASSIGN_USER_PROJECT = "ASSIGN_USER_PROJECT";

const UPDATE_TASK = "UPDATE_TASK";
const UPDATE_NOTE = "UPDATE_NOTE";
const CREATE_TASK = "CREATE_TASK";
const DELETE_TASK = "DELETE_TASK";

const CLEAR_MANAGER_VIEW = "CLEAR_MANAGER_VIEW";

module.exports = {
  GET_PROJECT_BY_ID,
  GET_TASKS_BY_PROJECT,
  GET_ASIGNED_USERS,
  UPDATE_TASK,
  DELETE_PROJECT,
  UPDATE_NOTE,
  CREATE_TASK,
  DELETE_TASK,
  GET_ALL_USERS,
  ASSIGN_USER_PROJECT,
  CLEAR_MANAGER_VIEW
};
