const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
const GET_TASKS_BY_PROJECT = "GET_TASKS_BY_PROJECT";
const GET_ASIGNED_USERS = "GET_ASIGNED_USERS";
const DELETE_PROJECT = "DELETE_PROJECT";

const UPDATE_TASK = "UPDATE_TASK";
const UPDATE_NOTE = "UPDATE_NOTE";
const CREATE_TASK = "CREATE_TASK";

module.exports = {
  GET_PROJECT_BY_ID,
  GET_TASKS_BY_PROJECT,
  GET_ASIGNED_USERS,
  UPDATE_TASK,
  DELETE_PROJECT,
  UPDATE_NOTE,
  CREATE_TASK,
};
