const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
const GET_TASKS_BY_PROJECT = "GET_TASKS_BY_PROJECT";
const GET_ASIGNED_USERS = "GET_ASIGNED_USERS";

module.exports = {
  GET_PROJECT_BY_ID,
  GET_TASKS_BY_PROJECT,
  GET_ASIGNED_USERS,
};
